version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    command: npm run start:dev 